### ISSUE TITLE
The num_classes during training and testing

### ISSUE THREAD

**Issue by weiyaowu-md** [salman-h-khan/PL-ZSD_Release#10]
hello, I want to ask you some questions about the num classes. Does the num_classes equal 65 and 80 during training and testing on MSCOCO dataset?

**Comment by shafin5** [comment]
In this implementation, during training and testing num_classes are 65 and 80 respectively. For GZSL, all 80 should be considered for inference. However, for ZSL only last 15 predictions are useful because the total number of unseen classes is 15.
