### ISSUE TITLE
for GZSD,when training,classification (Concatenate)    (None, None, 65) ? why not   (None, None, 80) ??

### ISSUE THREAD

**Issue by lixiangamy** [salman-h-khan/PL-ZSD_Release#15]

**Comment by lixiangamy** [comment]
if classification (Concatenate) (None, None, 65) ,how to test the unseen classs?

**Comment by shafin5** [comment]
In this work, unseen word vectors of 15 unseen classes are not used during training for both ZSD and GZSD. As there are 65 seen classes, it is (None, None, 65). During inference time the method uses 65+15 = 80 word vectors to perform both ZSD and GZSD tasks. For detail please check: https://github.com/salman-h-khan/PL-ZSD_Release/blob/master/keras_retinanet/utils/eval.py
