### ISSUE TITLE
The predicted scores are all zero.Have you seen this problem？

### ISSUE THREAD

**Issue by CaiQiuYu** [salman-h-khan/PL-ZSD_Release#16]
I used my own glove word2vec embedding data for my own dataset and vocabulary_glo.txt you provided.  I trained 1 epoch with 10000 iterations. The loss is just about 5. But when I use gzsd.py to predict and I found all the scores are zero.

**Comment by shafin5** [comment]
From my experience, I faced such problems when the predicted confident scores are not high enough to pass NMS. You can find a score_threshold during NMS process. Moreover, I suspect your training needs to perform more epochs. In my experiments, loss usually moves down below 1.

**Comment by CaiQiuYu** [comment]
> From my experience, I faced such problems when the predicted confident scores are not high enough to pass NMS. You can find a score_threshold during NMS process. Moreover, I suspect your training needs to perform more epochs. In my experiments, loss usually moves down below 1.

Thanks for your reply. Now I am trying to train the network with more epochs. I hope I can get a good performance. Your work is really inspiring.

**Comment by xiaofeng-c** [comment]
If you mainly use cpu when you train?I find the gpu is nearly not used when i train it.

**Comment by xiaofeng-c** [comment]
So a eppch training may cost nearly one day.
