### ISSUE TITLE
Have you tried applying the politary loss function to the traditional classification problem instead of the zero shot object classification problem? I would like to know whether the effect will be better or not.

### ISSUE THREAD

**Issue by Bigwode** [salman-h-khan/PL-ZSD_Release#5]
Have you tried applying the politary loss function to the traditional classification problem instead of the zero shot object classification problem? I would like to know whether the effect will be better or not.

**Comment by salman-h-khan** [comment]
Yes, we have tried the PL on the traditional detection problem (not classification as our base case is detection). We get comparable performance with the Focal Loss, which shows that the PL is specifically useful for ZSD case where proper alignment with the word-vectors and separation between background and unseen classes are important considerations.
