### ISSUE TITLE
Can you share train code? I want to know how to train this model. Thank you!

### ISSUE THREAD

**Issue by TessGreymane** [salman-h-khan/PL-ZSD_Release#6]

**Comment by salman-h-khan** [comment]
We have provided both training and evaluation codes. Please follow the instructions in Readme for training. 

We identified that at some places the readme file incorrectly mentioned only "eval" code, which we have now corrected to reflect both "train+eval" implementation.

**Comment by TessGreymane** [comment]
Thank you very much.
